### ISSUE TITLE
Issues when defining enum type in Data Structures

### ISSUE THREAD

**Issue by udoprog** [apiaryio/protagonist#129]
```javascript
var protagonist = require('protagonist');

test = (
    "# Data Structures\n" +
    "## TimeUnit (enum[string])\n" +
    "+ Members\n" +
    "    + `hello`"
);

protagonist.parse(test, function(error, result) {
    if (error) {
        console.log(error);
    } else {
        console.log(result);
    }
});
```
Output:
```
$> node test.js
{ code: 1,
  message: 'parser exception: \'mismatched adapter and node type\'',
  location: [] }
```

**Comment by kylef** [comment]
That's a very strange error message.

Seems to be a problem using the `members` type separator in an enum.

If you're looking for a short-term workaround while we resolve the problem, removing the members separator should act as a workaround:

```apib
# API Name
## Data Structures
### Time Unit (enum)

+ hello
```

```yaml
element: "parseResult"
content:
  -
    element: "category"
    meta:
      classes:
        - "api"
      title: "API Name"
    content:
      -
        element: "category"
        meta:
          classes:
            - "dataStructures"
        content:
          -
            element: "dataStructure"
            content:
              -
                element: "enum"
                meta:
                  id: "Time Unit"
                content:
                  -
                    element: "string"
                    content: "hello"
```
